### ISSUE TITLE
Review gem cleanup after bundle

### ISSUE THREAD

**Issue by simaishi** [ManageIQ/manageiq-rpm_build#1]
After running `bundle install`, files/directories not needed are deleted in gem_cleanup.sh. The contents are mostly taken from `kickstarts/partials/post/bundler.ks.erb` from manageiq-appliance-build repo, but this can be enhanced:

- ext directory for compiled gems and remove workaround added in https://github.com/ManageIQ/manageiq-rpm_build/blob/master/build_scripts/rpm_spec/manageiq-gemset/manageiq-gemset.spec#L70-L71:

```
# workaround
%{__rm} -rf %{buildroot}/%{app_root}/gems/ffi-*/ext
```
- rbnacl-libsodium creates 'vendor' and 'tmp' directories, together ~40MB or so

**Comment by Fryguy** [comment]
Closed via https://github.com/ManageIQ/manageiq-rpm_build/pull/92 and The first bullet was removed in https://github.com/ManageIQ/manageiq-rpm_build/pull/94.
