### ISSUE TITLE
Yanked mimemagic 0.3.5 breaks manageiq-rpm_build installation

### ISSUE THREAD

**Issue by UnderGrounder96** [ManageIQ/manageiq-rpm_build#143]
The gem mimemagic (see mimemagicrb/mimemagic#97 ) has resolved a licensing issue not long ago by yanking all old builds prior to 0.4.0.

Would it be possible to release new patches of jansa-3 (and others?) that relax this dependency to include 0.4.x?

**Steps to reproduce**
Attempt to build _jansa-3_ RPMs

**Expected behavior**
Successful installation

**Actual behavior**
 ---> bundle _2.1.4_ install --jobs 6 --retry 3
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this machine.
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Using bundler 2.1.4
Fetching bundler-inject 1.1.0
Installing bundler-inject 1.1.0
Installed plugin bundler-inject
Fetching source index from https://rubygems.manageiq.org/
Fetching gem metadata from https://rubygems.org/......
Your bundle is locked to mimemagic (0.3.5), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of mimemagic (0.3.5) has removed
it. You'll need to update your bundle to a version other than mimemagic (0.3.5) that hasn't been removed in order to install.

**Commands used**
    git clone -b jansa-3 https://github.com/manageiq/manageiq-rpm_build.git
    cd manageiq-rpm_build
    sudo docker build -t manageiq:jansa .
    sudo docker run --rm -tv ${PWD}/rpm_cache:/root/BUILD manageiq:jansa build --build-type release --git-ref jansa-3

**System configuration**
Centos 7
CPUs 6
RAM 16GB
Disk 80GB

**RubyGems Environment**
  - RUBYGEMS VERSION: 3.0.3
  - RUBY VERSION: 2.6.3 (2019-04-16 patchlevel 62) [x86_64-linux]
  - INSTALLATION DIRECTORY: /root/BUILD/manageiq-gemset-10.3.0
  - USER INSTALLATION DIRECTORY: /root/.gem/ruby
  - RUBY EXECUTABLE: /usr/bin/ruby
  - GIT EXECUTABLE: /bin/git
  - EXECUTABLE DIRECTORY: /root/BUILD/manageiq-gemset-10.3.0/bin
  - SPEC CACHE DIRECTORY: /root/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /root/BUILD/manageiq-gemset-10.3.0
     - /usr/share/gems
     - /usr/local/share/gems
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--no-ri --no-rdoc --no-document"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /root/BUILD/manageiq-gemset-10.3.0/bin
     - /usr/local/bin
     - /usr/local/sbin
     - /bin
     - /sbin
     - /usr/bin
     - /usr/sbin
     - /root/bin
     - ~/bin

**Comment by Fryguy** [comment]
@bdunne Can you take a look at this one?

**Comment by bdunne** [comment]
Jansa fixed by: https://github.com/ManageIQ/manageiq/pull/21337
