### ISSUE TITLE
Allow copr cli token to be mounted into the container

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-rpm_build#19]
Part of the script can be to write out the token from the ENV var to the known location (unless the copr CLI can also somehow take an ENV var.

**Comment by simaishi** [comment]
CLI doesn't take ENV var, so it has to be written to a file. FYI, the token is a file with 5 lines.
```
[copr-cli]
login = <generated by copr>
username = xxx
token = <generated by copr>
copr_url = https://copr.fedorainfracloud.org
```

**Comment by Fryguy** [comment]
> the token is a file with 5 lines.

oh that's interesting :/  Still could be an env var though, right?

`COPR_CLI_TOKEN="$(cat copr_cli_token)"`

**Comment by simaishi** [comment]
Yeah, we just have to make sure we don't print out the file contents 😄

**Comment by Fryguy** [comment]
As discussed we can do this by allowing the caller to mount their token at `~/.config/copr`.
