### ISSUE TITLE
Fix release script missing version numbers

### ISSUE THREAD

**Issue by bdunne** [ManageIQ/manageiq-rpm_build#199]
The release script needs to updated to handle some missing cases.  Below examples show the changes that were manually made that need to be added to the release script.

- https://github.com/ManageIQ/manageiq-rpm_build/pull/198#issuecomment-923005099
- https://github.com/ManageIQ/manageiq-rpm_build/pull/189

**Comment by Fryguy** [comment]
@bdunne Was this closed by another PR?
