### ISSUE TITLE
Add productization support

### ISSUE THREAD

**Issue by simaishi** [ManageIQ/manageiq-rpm_build#2]

**Comment by Fryguy** [comment]
So far, outside of a normal plugin the only things I've seen are needing a way to handle:

- manageiq-ui-service skin - I think I can make this "pluggable" via a rake task in the manageiq-ui-service repo itself which can "find" the directories in the plugins and then symlink the expected values.  This rake task would have to be called during RPM build
- static assets in /public - if a plugin brings static assets in the public directory, this works fine in development mode, but in production mode the assets are behind apache and served from /var/www/miq/vmdb/public directly.  I think this can be handled by an extra step during rpm build to copy into the vmdb/public directory if a plugin brings static assets

**Comment by simaishi** [comment]
Make sure VERSION file update is handled as well.

**Comment by Fryguy** [comment]
I think this one is done for all intents.  Closing now and we can reopen with other issues if we stumble on them.
