### ISSUE TITLE
Master appliance build failure

### ISSUE THREAD

**Issue by bdunne** [ManageIQ/manageiq-rpm_build#219]
Master appliance builds have been failing with `Error in POSTIN scriptlet in rpm package manageiq-core` see:
![factory-build-28da4639-7cf2-4982-827d-9ae3ba9dd226-1634657378 141397](https://user-images.githubusercontent.com/651659/138349097-53e9e8ab-f79d-4ff3-9672-00dd1de7670c.jpg)

**Comment by kbrock** [comment]
So the rpms work for upgrade. They fail in Kickstarter. So there is something in here that is part of our appliance but is not part of the base layer install.

I said I would look into user creation (manageiq user). I need to circle back to see if we need to declare any other requirements for that

**Comment by kbrock** [comment]
@bdunne are we all set to close this now?

**Comment by bdunne** [comment]
Master builds are working, closing
