### ISSUE TITLE
rpm version/release number update for nightly/tag builds

### ISSUE THREAD

**Issue by simaishi** [ManageIQ/manageiq-rpm_build#4]
The rpm is currently using `Release:  1.<build_date>%{?dist}` for the rpm 'release' in N-V-R.

This needs to be changed to:

- include manageiq core repo sha for nightly build (I think...)
- include the tag name for tag build

**Comment by Fryguy** [comment]
I'm ok if the NVR only has the numerical version and we include the SHA and tag name *inside* the build (I think we already do in the BUILD/VERSION/RELEASE files)

**Comment by simaishi** [comment]
@Fryguy took what we've discussed and changed a bit based on the guidelines (https://docs.fedoraproject.org/en-US/packaging-guidelines/Versioning/)

jansa (nightly) - 10.1.0-0.1.yyyymmddhhmmss
jansa-1-alpha1 - 10.1.0-0.2.alpha1
jansa (nightly) - 10.1.0-0.2.yyyymmddhhmmss
jansa-1-beta1 - 10.1.0-0.3.beta1
jansa-1 - 10.1.0-1
jansa-2 - 10.2.0-1
jansa-2.1 - 10.2.1-1
jansa-2.1 (but with RPM change) - 10.2.1-2

The nightly isn't following 100% as we don't include git sha, but packages will be updated properly with the above.

```
$ rpmdev-vercmp 10.1.0-0.1.20200423000000.el8 10.1.0-0.2.alpha1.el8
10.1.0-0.1.20200423000000.el8 < 10.1.0-0.2.alpha1.el8

$ rpmdev-vercmp 10.1.0-0.2.alpha1.el8 10.1.0-0.2.20200424000000.el8
10.1.0-0.2.alpha1.el8 < 10.1.0-0.2.20200424000000.el8

$ rpmdev-vercmp 10.1.0-0.3.beta1.el8 10.1.0-1.el8
10.1.0-0.3.beta1.el8 < 10.1.0-1.el8
```

**Comment by Fryguy** [comment]
What is the number after the -0, but before the timestamp? Is it necessary?  I'm concerned it will get complicated keeping that value stored somewhere for successive nightly builds.

**Comment by simaishi** [comment]
That's necessary to keep the update work. Without it, digits (timestamp) > pre-release name (alpha, beta, etc.) and you won't be able to update from nightly to pre-releases.

I'm thinking we can have a rake task to increment that digit when we tag, just like how we modify VERSION file for the core repo.

**Comment by Fryguy** [comment]
oh i see...so like another file?  I'd be ok with that.
