### ISSUE TITLE
Disable rsyslog/journald log copies on appliances

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-rpm_build#411]
Opening this issue to discuss.  The way to implement this is to remove im_journal module lines from /etc/rsyslog.conf, however since we don't own that file, it will require a post script in the appliance RPM.  Is there a downside to doing this?

@agrare @bdunne  Thoughts?

**Comment by agrare** [comment]
Okay had to dust off my unix handbook to get this done :laughing: 
https://github.com/ManageIQ/manageiq-rpm_build/pull/426 will comment out all lines starting with `module(load="imjournal"` and ending with `StateFile="imjournal.state")`
