### ISSUE TITLE
Update yum repo should only update for the specified release/branch?

### ISSUE THREAD

**Issue by simaishi** [ManageIQ/manageiq-rpm_build#60]
When build runs for 'master', yum repo update happens not only for 'master' but also for 'jansa'.

```
Uploading: release/10-jansa/el8/ppc64le/repmgr10-4.0.6-1.el8.ppc64le.rpm
...
Uploading: release/11-kasparov/el8/ppc64le/repmgr10-4.0.6-1.el8.ppc64le.rpm
```
Is that expected?

I'm thinking that's why yesterday's jansa nightly failed updating yum repo:

```
/usr/share/ruby/fileutils.rb:1386:in `initialize': No such file or directory @ rb_sysopen - /tmp/d20200604-51-1fugxbo/release/10-jansa/el8/ppc64le/repmgr10-4.0.6-1.el8.ppc64le.rpm (Errno::ENOENT)
```
Also, #59 isn't backported to jansa yet, so why does jansa build even care about ppc64le?

**Comment by bdunne** [comment]
Whenever the script is run, it will update all of the repos.  That was intentional, we can try to split it up.  FWIW, I still think it's strange to have this here.

**Comment by simaishi** [comment]
If it's supposed to update all repos, I think it doesn't make sense to have config per branch. I'm good with moving this elsewhere - just not sure where this should belong.

**Comment by simaishi** [comment]
So this is causing another problem.  We currently run nightly build for master and jansa branches - rpm build followed by appliance/container build. master and jansa builds run independently on different machines and it's a problem if jansa rpm build updates yum repo while master appliance build is running as it can no longer find the metadata file.
