### ISSUE TITLE
Ensure 3 RPMs used in appliance build are from the same build

### ISSUE THREAD

**Issue by simaishi** [ManageIQ/manageiq-rpm_build#9]
Currently, 3 RPMs (manageiq, manageiq-gemset and manageiq-appliance) are built independently in Copr and any one of them could fail.

We need to put some kind of mechanism to make sure appliance build will pick up matching RPMs.

The easiest way is to "Require" the exact same version-release. Alternatively, we can have 1 RPM spec file to build all RPMs as sub packages.

**Comment by Fryguy** [comment]
Can we use the timestamp from the start of the build and make them match?

**Comment by Fryguy** [comment]
> Alternatively, we can have 1 RPM spec file to build all RPMs as sub packages.

I really like this idea.  What would be the RPM structure?

- manageiq
  - manageiq-core ?
  - manageiq-gemset
  - manageiq-appliance

**Comment by simaishi** [comment]
> Can we use the timestamp from the start of the build and make them match?

In the re-org work, I'm setting

BUILD_DATE   = Time.now.strftime("%Y%m%d%H%M%S")

and use that for BUILD file as well as in R part of RPM N-V-R.

**Comment by simaishi** [comment]
> * manageiq
>   
>   * manageiq-core ?
>   * manageiq-gemset
>   * manageiq-appliance

That sounds good. manageiq-appliance is currently split to 3 RPMs:

- manageiq-appliance (used in appliance only - mostly packages not needed on pods, like httpd, external auth stuff, etc.)
- manageiq-appliance-tools (wget, vim, etc. - tools not 'required' by the app itself, but useful to have)
- manageiq-appliance-common (needed in both appliance and pods)

So maybe we can do something like this?

- manageiq <-- empty
  - manageiq-core
  - manageiq-gemset
  - manageiq-appliance-common
  - manageiq-appliance-\<something that identifies as appliance only\>
  - manageiq-appliance-tools

So under "manageiq" package, 5 RPMs will be built.

The RPM dependencies will continue to be:

`manageiq-appliance-<something>` -> `manageiq-appliance-common` -> `manageiq-core` -> `manageiq-gemset`

appliance build will install "manageiq-appliance-\<something\>" and "manageiq-appliance-tools" 

pods build will install "manageiq-appliance-common"

**Comment by Fryguy** [comment]
Sounds good to me :+1:

**Comment by Fryguy** [comment]
Some thoughts on manageiq-appliance-<something>:

manageiq-appliance-vms
manageiq-appliance-virtualization
manageiq-appliance-virtualized
(or maybe just keep it manageiq-appliance?)

---

If we have a different set of rpms installed for pods vs appliance, I'm not sure it makes sense to have the top level manageiq empty rpm, because then how would you know what sub-rpms to install?

Maybe something like this is better? It's 2 top level RPMs clearly describing the target of each.

- manageiq-appliance-vms (what is currently manageiq-appliance)
  - manageiq-appliance-tools
  - manageiq-appliance-common
    - manageiq-core
      - manageiq-gemset
- manageiq-appliance-pods (empty)
  - manageiq-appliance-common
    - manageiq-core
      - manageiq-gemset
  
Naming-wise, I could alternately see the 2 top-level RPMs being `manageiq-appliance` and `manageiq-pods`.  Additionally, if we don't have a top-level `manageiq` rpm, then instead of `manageiq-core` that one can just be named `manageiq`.

**Comment by simaishi** [comment]
Having a separate top RPM for appliance and pods makes sense, so it's clear what to install.  But I think we still need something at the very top and make everything else sub packages. Otherwise, we'll need to build 2 core, 2 gemset, etc.

So how about this...  "manageiq" package builds all manageiq-* RPMs as sub packages. "manageiq" itself is just a package name and no RPM is built for it.

Appliance:
- manageiq-appliance
  - manageiq-appliance-tools
  - manageiq-system(?)  - what's currently manageiq-appliance-common
  - manageiq-ui
    - manageiq-core
      - manageiq-gemset

Pods manageiq-base image:
- manageiq-pods-base (or just manageiq-pods)
  - manageiq-system
  - manageiq-core
    - manageiq-gemset

Pods manageiq-ui-worker image:
- manageiq-ui

What's currently `manageiq` is split to `manageiq-core` and `manageiq-ui` as I realized we don't want to install ui stuff (~120MB) in manageiq-base for pods.

**Comment by Fryguy** [comment]
This sounds great!  What is the content of manageiq-appliance-common?

> manageiq-pods-base (or just manageiq-pods) 

I like `manageiq-pods`

**Comment by simaishi** [comment]
manageiq-appliance-common currently contains most of manageiq-appliance repo contents (which should be revisited) + it brings in a few common packages (e.g. logrotate)

**Comment by Fryguy** [comment]
Even logrotate doesn't make sense in pods, as we are considering eliminate filesystem logs altogether.  We should definitely review the contents of that RPM, but for now I like what you've come up with.
